In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.datasets import fetch_openml

mnist = fetch_openml('mnist_784', version=1)

X = mnist.data   # features (784 pixels)
y = mnist.target # labels (0–9)

print(X.shape, y.shape)

(70000, 784) (70000,)

In [5]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X, y,test_size=0.2,random_state=2)

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [7]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [8]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\rohit\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\sklearn\linear_model\_logistic.py:406: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

DecisionTreeClassifier()

In [9]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [10]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.9232142857142858
Accuracy of Decision Trees 0.8725

In [11]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,10)))

Logistic Regression Confusion Matrix

      0     1     2     3     4     5     6     7     8     9
0  1358     0     5     1     3     9     8     4     4     4
1     0  1505     6     5     1     7     1     7    15     2
2     6    20  1227    24    13     8    22    17    31     2
3     8     8    29  1301     1    47     6    14    32    11
4     3     8    11     6  1258     0    14     4    10    49
5     9     8     8    44    12  1100    29     9    31     9
6     7     3    14     2    11    14  1381     2     2     2
7     7     3    14     8    13     3     1  1364     6    46
8    11    24    18    33     3    41     8     3  1174    18
9     6     3     3    16    32    17     0    26    10  1257

In [12]:
print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,10)))

Decision Tree Confusion Matrix

      0     1     2     3     4     5     6     7     8     9
0  1300     1    18    11     5    21    15     3    11    11
1     6  1481     9    10     4     3     9    11    11     5
2    19    15  1148    34    18    17    29    35    46     9
3     8     9    32  1236    10    62    12    26    33    29
4     6     5    16     5  1171    10    20    26    34    70
5    16    10     7    59    11  1050    31    12    44    19
6    19     9    17     6    23    36  1298     3    13    14
7     3     8    37    22    14     7     1  1320    12    41
8    16    26    33    24    33    52    21    16  1079    33
9    10     2    19    20    78    31     6    44    28  1132

In [13]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [15]:
precision_score(y_test,y_pred1,average='weighted')

0.9230357644112168

In [17]:
recall_score(y_test,y_pred1,average='weighted')

0.9232142857142858

In [16]:
f1_score(y_test,y_pred1,average='weighted')

0.9230567159226124

In [18]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

           0       0.96      0.97      0.97      1396
           1       0.95      0.97      0.96      1549
           2       0.92      0.90      0.91      1370
           3       0.90      0.89      0.90      1457
           4       0.93      0.92      0.93      1363
           5       0.88      0.87      0.88      1259
           6       0.94      0.96      0.95      1438
           7       0.94      0.93      0.94      1465
           8       0.89      0.88      0.89      1333
           9       0.90      0.92      0.91      1370

    accuracy                           0.92     14000
   macro avg       0.92      0.92      0.92     14000
weighted avg       0.92      0.92      0.92     14000