In [33]:
import numpy as np
import pandas as pd

In [34]:
df = pd.read_csv("car.csv")

In [35]:
df.head()

,name,year,selling_price,km_driven,fuel,seller_type,transmission,owner
0,Maruti 800 AC,2007,60000,70000,Petrol,Individual,Manual,First Owner
1,Maruti Wagon R LXI Minor,2007,135000,50000,Petrol,Individual,Manual,First Owner
2,Hyundai Verna 1.6 SX,2012,600000,100000,Diesel,Individual,Manual,First Owner
3,Datsun RediGO T Option,2017,250000,46000,Petrol,Individual,Manual,First Owner
4,Honda Amaze VX i-DTEC,2014,450000,141000,Diesel,Individual,Manual,Second Owner

In [36]:
df = df[['name', 'km_driven', 'fuel', 'owner', 'selling_price']]

In [37]:
df.head()

                       name  km_driven    fuel         owner  selling_price
0             Maruti 800 AC      70000  Petrol   First Owner          60000
1  Maruti Wagon R LXI Minor      50000  Petrol   First Owner         135000
2      Hyundai Verna 1.6 SX     100000  Diesel   First Owner         600000
3    Datsun RediGO T Option      46000  Petrol   First Owner         250000
4     Honda Amaze VX i-DTEC     141000  Diesel  Second Owner         450000

In [38]:
df['brand'] = df['name'].apply(lambda x: x.split()[0])

In [39]:
df.head()

,name,km_driven,fuel,owner,selling_price,brand
0,Maruti 800 AC,70000,Petrol,First Owner,60000,Maruti
1,Maruti Wagon R LXI Minor,50000,Petrol,First Owner,135000,Maruti
2,Hyundai Verna 1.6 SX,100000,Diesel,First Owner,600000,Hyundai
3,Datsun RediGO T Option,46000,Petrol,First Owner,250000,Datsun
4,Honda Amaze VX i-DTEC,141000,Diesel,Second Owner,450000,Honda

In [40]:
df = df[['brand', 'km_driven', 'fuel', 'owner', 'selling_price']]

In [41]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti      70000  Petrol   First Owner          60000
1   Maruti      50000  Petrol   First Owner         135000
2  Hyundai     100000  Diesel   First Owner         600000
3   Datsun      46000  Petrol   First Owner         250000
4    Honda     141000  Diesel  Second Owner         450000

In [42]:
df['owner'].value_counts()

owner
First Owner             2832
Second Owner            1106
Third Owner              304
Fourth & Above Owner      81
Test Drive Car            17
Name: count, dtype: int64

ONE HOT ENCODING USING PANDAS

In [43]:
pd.get_dummies(df, columns= ['fuel', 'owner'], dtype= int)

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,70000,60000,0,0,0,0,1,1,0,0,0,0
1,Maruti,50000,135000,0,0,0,0,1,1,0,0,0,0
2,Hyundai,100000,600000,0,1,0,0,0,1,0,0,0,0
3,Datsun,46000,250000,0,0,0,0,1,1,0,0,0,0
4,Honda,141000,450000,0,1,0,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai,80000,409999,0,1,0,0,0,0,0,1,0,0
4336,Hyundai,80000,409999,0,1,0,0,0,0,0,1,0,0
4337,Maruti,83000,110000,0,0,0,0,1,0,0,1,0,0
4338,Hyundai,90000,865000,0,1,0,0,0,1,0,0,0,0
4339,Renault,40000,225000,0,0,0,0,1,1,0,0,0,0

K - 1 OneHotEncoding

In [44]:
pd.get_dummies(df, columns= ['fuel', 'owner'], dtype= int, drop_first= True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_Electric,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,70000,60000,0,0,0,1,0,0,0,0
1,Maruti,50000,135000,0,0,0,1,0,0,0,0
2,Hyundai,100000,600000,1,0,0,0,0,0,0,0
3,Datsun,46000,250000,0,0,0,1,0,0,0,0
4,Honda,141000,450000,1,0,0,0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...
4335,Hyundai,80000,409999,1,0,0,0,0,1,0,0
4336,Hyundai,80000,409999,1,0,0,0,0,1,0,0
4337,Maruti,83000,110000,0,0,0,1,0,1,0,0
4338,Hyundai,90000,865000,1,0,0,0,0,0,0,0
4339,Renault,40000,225000,0,0,0,1,0,0,0,0

3. OneHotEncoding using Sklearn

In [45]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti      70000  Petrol   First Owner          60000
1   Maruti      50000  Petrol   First Owner         135000
2  Hyundai     100000  Diesel   First Owner         600000
3   Datsun      46000  Petrol   First Owner         250000
4    Honda     141000  Diesel  Second Owner         450000

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 0:4], df.iloc[:, -1], test_size= 0.2)

In [47]:
X_train.head()

          brand  km_driven    fuel         owner
1002    Hyundai      10000  Diesel   First Owner
1368     Maruti     143000  Petrol   Third Owner
639   Chevrolet      66000  Diesel   First Owner
451      Maruti      80000  Diesel  Second Owner
3265     Maruti      34000  Petrol   First Owner

In [48]:
X_test.head()

       brand  km_driven    fuel         owner
1016  Maruti      60000  Petrol  Second Owner
1230  Maruti     112880  Diesel   First Owner
507     Ford      91086  Petrol  Second Owner
1792  Maruti      80000  Petrol   First Owner
2672  Maruti     220000  Diesel   First Owner

In [49]:
from sklearn.preprocessing import OneHotEncoder

In [55]:
ohe = OneHotEncoder(drop='first', dtype= np.int32)

In [56]:
X_train_new = ohe.fit_transform(X_train[['fuel', 'owner']]).toarray()

In [57]:
X_test_new = ohe.fit_transform(X_test[['fuel', 'owner']]).toarray()

In [58]:
X_train_new

array([[1, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 1],
       [1, 0, 0, ..., 0, 0, 0],
       ...,
       [1, 0, 0, ..., 0, 0, 0],
       [1, 0, 0, ..., 1, 0, 0],
       [1, 0, 0, ..., 1, 0, 0]], shape=(3472, 8), dtype=int32)

In [60]:
np.hstack((X_train[['brand', 'km_driven']].values, X_train_new))

array([['Hyundai', 10000, 1, ..., 0, 0, 0],
       ['Maruti', 143000, 0, ..., 0, 0, 1],
       ['Chevrolet', 66000, 1, ..., 0, 0, 0],
       ...,
       ['Toyota', 75000, 1, ..., 0, 0, 0],
       ['Tata', 80000, 1, ..., 1, 0, 0],
       ['Mahindra', 89000, 1, ..., 1, 0, 0]],
      shape=(3472, 10), dtype=object)

4. OneHotEncoding with top categories

In [62]:
counts = df['brand'].value_counts()

In [63]:
df['brand'].nunique()

29

In [64]:
threshold = 100

In [66]:
repl = counts[counts <= threshold].index

In [69]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon'), dtype= int).sample(5)

,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Tata,Toyota,Volkswagen,uncommon
2582,0,0,0,0,0,0,0,0,0,0,1
3780,0,0,0,0,0,0,0,0,1,0,0
3247,0,1,0,0,0,0,0,0,0,0,0
649,0,0,0,0,0,1,0,0,0,0,0
300,0,0,0,1,0,0,0,0,0,0,0